# Generated by Django 2.0.5 on 2019-02-19 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('www_name', models.CharField(max_length=32, unique=True)),
                ('www_dir', models.CharField(max_length=64)),
                ('old_server_version', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Cron_git',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.CharField(max_length=24, unique=True)),
                ('create_username', models.CharField(max_length=64, unique=True)),
                ('create_time', models.CharField(max_length=24)),
                ('atq_id', models.IntegerField(unique=True)),
                ('www_name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ManageOps.Code_version', to_field='www_name')),
            ],
        ),
        migrations.CreateModel(
            name='Linux_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ssh_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('host', models.CharField(max_length=128)),
                ('competence', models.CharField(max_length=128, null=True)),
                ('create_time', models.CharField(max_length=32)),
            ],
        ),
    ]
