# Generated by Django 2.0.5 on 2019-02-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageOps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron_git',
            name='run_time',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterUniqueTogether(
            name='cron_git',
            unique_together={('www_name', 'run_time')},
        ),
    ]
