# Generated by Django 2.0.5 on 2019-02-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageOps', '0002_auto_20190222_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='cron_git',
            name='cron_shell_file_path',
            field=models.CharField(default='xxx', max_length=128),
        ),
    ]
