# Generated by Django 2.0.5 on 2019-02-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageOps', '0003_cron_git_cron_shell_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron_git',
            name='cron_shell_file_path',
            field=models.CharField(max_length=128),
        ),
    ]
